### ISSUE TITLE
DBClusterParameterGroupNotFound

### ISSUE THREAD

**Issue by mikhaelsantos** [aws-quickstart/quickstart-r3-corda#25]
I keep getting this error when deploying the CF template, when clicking on New VPC
`Service: AmazonRDS; Statu s Code: 404; Error Code: DBClusterParameterGroupNotFound;`

**Comment by mikhaelsantos** [comment]
I created : default.aurora-postgresql9.6

But now get the following error:
`The Parameter Group default.aurora-postgresql9.6 with DBParameterGroupFamily aurora-postgresql9.6 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily aurora-postgresql10 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: fefcdb88-907b-40fd-9b6f-144ac01340a5)`

**Comment by avattathil** [comment]
Cleaning up..

Should be fixed in e2f107d9ae0464362e700507b667e46b2ff865fd. Please reopen if this is still an issue
